name: Compile C Code

on:
  push:
    paths:
      - 'src/*.c'
  pull_request:
    paths:
      - 'src/*.c'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up build environment
      run: |
        sudo apt-get update
        sudo apt-get -y install build-essential

    - name: Compile C code
      run: gcc -o src/gitready_pre src/*.c

    - name: Copy compiled executable to src directory
      run: cp src/gitready_pre src/gitready

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: gitready
        path: src/gitready

    - name: Run compiled code
      run: ./src/gitready
